apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ= 
  DB_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_PORT: MzMwNg== 
  DB_NAME: dG9kb19kYg==