apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ= 
  DB_HOST: bXlzcWwtcHJpbWFyeS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_PORT: MzMwNg== 
  DB_NAME: dG9kb19kYg==
